CFLAGS=-Wall -g

all: clean crash decompose max_min swap split_time find_two_largest pointer_stack

clean:
	rm -f crash
	rm -f decompose
	rm -f max_min
	rm -f swap
	rm -f split_time
	rm -f find_two_largest
	rm -f pointer_stack
