CFLAGS=-Wall -g

all: clean strings initialize command_line_name implement days_of_week string_block remind planets deal

clean:
	rm -f strings
	rm -f initialize
	rm -f command_line_name
	rm -f implement
	rm -f days_of_week
	rm -f string_block
	rm -f remind
	rm -f planets
	rm -f deal
