CFLAGS=-Wall -g

all: clean digits add_numbers goto max_val proper_fraction broker squares square3 print_month

clean:
	rm -f digits
	rm -f add_numbers
	rm -f goto
	rm -f max_val
	rm -f proper_fraction
	rm -f broker
	rm -f squares
	rm -f square3
	rm -f print_month
