CFLAGS=-Wall -g

all: clean sizeof conversion exercises squares_table sum square_prompt phone_number scrabble airline

clean:
	rm -f sizeof
	rm -f conversion
	rm -f exercises
	rm -f squares_table
	rm -f sum
	rm -f square_prompt
	rm -f phone_number
	rm -f scrabble
	rm -f airline
