CFLAGS=-Wall -g

all: clean digits military broker beaufort income_tax grade cardinal

clean:
	rm -f digits
	rm -f military
	rm -f broker
	rm -f beaufort
	rm -f income_tax
	rm -f grade
	rm -f cardinal
