CFLAGS=-Wall -g

all: clean broker date digits military income_tax beaufort grade cardinal broker2 upc

clean:
	rm -f broker
	rm -f date
	rm -f digits
	rm -f military
	rm -f income_tax
	rm -f beaufort
	rm -f grade
	rm -f cardinal
	rm -f broker2
	rm -f upc
