CFLAGS=-Wall -g

interest: interest.c
	${CC} ${CFLAGS} interest.c -lm -o $@

all: clean array_stats biff grades interest random_walk repeats repeats2 repeats3 repeats4 reverse

clean:
	rm -f array_stats
	rm -f biff
	rm -f grades
	rm -f interest
	rm -f random_walk
	rm -f repeats
	rm -f repeats2
	rm -f repeats3
	rm -f repeats4
	rm -f reverse
