CFLAGS=-Wall -g

all: clean broker digit_count military beaufort income_tax grades cardinal

clean:
	rm -f broker
	rm -f digit_count
	rm -f military
	rm -f beaufort
	rm -f income_tax
	rm -f grades
	rm -f cardinal
